# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: echo Build
    - script: sleep 20
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Unit Tests - RapDev'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'jon-devops-auto.war - AUTO'
        publishLocation: 'Container'

- stage: DevDeploy
  dependsOn: Build
  condition: false
  jobs:
  - job: 'DevDeploy'
    steps:
    - script: echo Dev Deploy

- stage: TestDeploy
  dependsOn: DevDeploy
  condition: false
  jobs:
  - job: 'DevDeploy'
    steps:
    - script: echo Test Deploy

- stage: StageDeploy
  dependsOn: Build
  jobs:
  - job: 'DevDeploy'
    steps:
    - script: echo Stage Deploy

- stage: 'SNChange'
  dependsOn: StageDeploy
  jobs:
  - job: 'SNPackageRegistration'
    steps:
    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'dev229276-Jon - DevOps-ServiceNow DevOps Service Connection'
        packageName: "Package - $(Build.BuildId)"
        artifactsPayload: |
          {
              "artifacts": [
              {
                  "name": "jon-devops-auto.war - AUTO",
                  "repositoryName": "Auto Artifact",
                  "version": "1.$(build.buildId)",
                  "currentBuildInfo": "true"
              }]
          }
  
  - job: 'SNChange'
    pool: server
    dependsOn: 'SNPackageRegistration'
    steps:
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'dev229276-Jon - DevOps-ServiceNow DevOps Service Connection'    
