name: Deploy

on:
  workflow_dispatch:
    inputs:
      artifact_version:
        required: true
        type: string

jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run a one-line script
        run: echo Hello
            
  package-registration:
    needs: mytest
    runs-on: ubuntu-latest
    steps:
      - name: SN Register Artifact
        uses: ServiceNow/servicenow-devops-register-package@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          instance-url: ${{ secrets.SN_URL }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          artifacts: '[{"name": "jon-test-open2", "version": "${{ inputs.artifact_version }}", "repositoryName": "${{ github.repository }}"}]'
          package-name: 'Demo Package - ${{ github.run_number }}'
      - name: ServiceNow DevOps Change Automation
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          instance-url: ${{ secrets.SN_URL }}
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          job-name: ${{ github.job }}
          context-github: ${{ toJSON(github) }}
          change-request: '{}'
          deployment-gate: '{"environment":"Production","jobName":"My deploy test"}'
      

  deploy:
    name: My deploy test
    needs: package-registration
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run a one-line script
        run: echo Hello, world!
