name: Deploy-Test

on:
  workflow_dispatch:

jobs:

  deploy1:
    environment: prod1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  deploy2:
    needs: deploy1
    environment: prod1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
